version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"

  scheduler:
    image: alpine:latest
    depends_on:
      - app
    entrypoint: >
      /bin/sh -c "apk update && apk add --no-cache curl busybox && \
      curl -X GET http://app:8000/scrape && \
      echo '*/50 * * * * curl -X GET http://app:8000/scrape' > /etc/crontabs/root && \
      crond -f -l 8"
